# name: "Build Android app"

# on:
#   workflow_dispatch:
#     branches: [dev]
#     # can add push and pull_request here 

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Install Java
#         uses: actions/setup-java@v2
#         with:
#           java-version: "11"
#           distribution: "adopt"
#           cache: "gradle"

#       - name: Validate Gradle wrapper
#         uses: gradle/wrapper-validation-action@v1

#       - name: Setup Node  
#         uses: actions/setup-node@v3
#         with:
#           node-version: '16'

#       - name: Run Yarn Install
#         run: |
#              cd ./packages/rith_laundry/
#              npm i -g corepack
#              yarn install             
#       - name: Build application
#         run: |
#              cd ./packages/rith_laundry/android
#              ./gradlew assembleDebug             
#       - name: Upload application
#         uses: actions/upload-artifact@v2
#         with:
#           name: app
#           path: ./packages/rith_laundry/android/app/build/outputs/apk/debug/app-debug.apk
#           retention-days: 3
#           token: ${{ secrets.GITHUB_TOKEN }}


##################################################################
name: Build Android Release APK and Publish to Github Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Install Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Install dependencies
      run: yarn

    - name: Build the app
      run: yarn run android:build
#       run: yarn run android:build:release

    # - name: Archive the artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: android-release
    #     path: ${{ github.workspace }}/android/app/build/outputs/apk/release/app-armeabi-v7a-release.apk
    - name: Push to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ github.workspace }}/android/app/build/outputs/apk/release/*"
        tag: v1.0.${{ github.run_number }}
        token: ${{ secrets.TOKEN }} 

    # - name: Create Github Release
    #   uses: actions/create-release@v1
    #   with:
    #     tag_name: v${{ github.ref }}
    #     release_name: Release ${{ github.ref }}
    #     body: Release ${{ github.ref }}
    #     draft: false
    #     prerelease: false

    # - name: Upload APK to Github Release
    #   uses: actions/upload-release-asset@v1
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ${{ github.workspace }}/android/app/build/outputs/apk/release/app-armeabi-v7a-release.apk
    #     asset_name: app-armeabi-v7a-release.apk
    #     asset_content_type: application/vnd.android.package-archive
